"""add release date

Revision ID: 152ab9ea85a8
Revises: 2234ef1b46a1
Create Date: 2026-06-22 00:19:31.887487

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '152ab9ea85a8'
down_revision: Union[str, Sequence[str], None] = '2234ef1b46a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('release_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'release_date')
    # ### end Alembic commands ###
