"""Change release date type

Revision ID: 1653feea9e04
Revises: 152ab9ea85a8
Create Date: 2026-06-22 01:31:50.067410

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1653feea9e04'
down_revision: Union[str, Sequence[str], None] = '152ab9ea85a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games') as batch_op:
        batch_op.alter_column('release_date',
                   existing_type=sa.DATETIME(),
                   type_=sa.Date(),
                   existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games') as batch_op:
        batch_op.alter_column('release_date',
                   existing_type=sa.Date(),
                   type_=sa.DATETIME(),
                   existing_nullable=True)
    # ### end Alembic commands ###
