"""Add usergame

Revision ID: 523324bd5288
Revises: c41d1ba9cd80
Create Date: 2026-07-22 17:14:02.340976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '523324bd5288'
down_revision: Union[str, Sequence[str], None] = 'c41d1ba9cd80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usergame',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('hours_played', sa.Float(), nullable=False),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('status', postgresql.ENUM('backlog', 'playing', 'completed', 'dropped', name='gamestatus', create_type=False), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'game_id')
    )
    op.drop_column('games', 'added_at')
    op.drop_column('games', 'hours_played')
    op.drop_column('games', 'rating')
    op.drop_column('games', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('status', postgresql.ENUM('backlog', 'playing', 'completed', 'dropped', name='gamestatus'), autoincrement=False, nullable=False))
    op.add_column('games', sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('games', sa.Column('hours_played', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('games', sa.Column('added_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_table('usergame')
    # ### end Alembic commands ###
