"""steam fields on games and usergame

Revision ID: 858704172fa4
Revises: 551f60027532
Create Date: 2026-09-26 18:46:33.223162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '858704172fa4'
down_revision: Union[str, Sequence[str], None] = '551f60027532'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('steam_appid', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('steam_icon_hash', sa.String(), nullable=True))
    op.alter_column('games', 'genre',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.create_unique_constraint('uq_games_steam_appid', 'games', ['steam_appid'])
    op.alter_column(
        "usergame",
        "hours_played",
        new_column_name="playtime_minutes",
        type_=sa.Integer(),
        existing_type=sa.Float(),
        postgresql_using="ROUND(hours_played * 60)::integer",
    )
    op.add_column('usergame', sa.Column('last_played_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usergame', 'last_played_at')
    op.alter_column(
        "usergame",
        "playtime_minutes",
        new_column_name="hours_played",
        type_=sa.Float(),
        existing_type=sa.Integer(),
        postgresql_using="playtime_minutes::float / 60",
    )
    op.drop_constraint('uq_games_steam_appid', 'games', type_='unique')
    op.alter_column('games', 'genre',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.drop_column('games', 'steam_icon_hash')
    op.drop_column('games', 'steam_appid')
    # ### end Alembic commands ###
