"""add steam_id to users

Revision ID: e2996f0da3cd
Revises: 858704172fa4
Create Date: 2026-09-30 01:00:59.171473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2996f0da3cd'
down_revision: Union[str, Sequence[str], None] = '858704172fa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('steam_id', sa.String(length=17), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'steam_id')
    # ### end Alembic commands ###
